version: '3'

services:
  postrges:
    image: 'postgres:15-alpine'
    container_name: 'postgres'
    restart: always
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=DB'
      - 'POSTGRES_URL=jdbc:postgresql://postgres/DB'
#    expose:
#      - 5432
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data/
#    networks:
#      - ps


  app:
    build: ./
    container_name: 'java-app'
    ports:
      - '8080:8080'
    links:
      - 'postrges'
    depends_on:
      - postrges
    volumes:
      - app_data:/var/www/html
#    networks:
#      - ps

volumes:
  pgdata:
    external: true
  app_data:
#networks:
#  ps:
